whisperer(){
    echo -e "\e[1;31m-------------------------- SPLIT -------------------------------\e[0m"
    echo "lib32-catalyst-utils is now splitted into:"
    echo "lib32-catalyst-utils"
    echo "lib32-catalyst-libgl"
    echo "lib32-opencl-catalyst"
    echo -e "\e[1;31m----------------------------------------------------------------\e[0m"
}

post_install() {
    whisperer
}

post_upgrade() {
    whisperer
}