image: chakralinux/makepkg:latest

variables:
  REPODIR: "$CI_PROJECT_DIR"

stages:
  - build
  - sign
  - deploy

before_script:
  # import the gitlab-ci scripts
  - git clone --depth 1 https://code.chakralinux.org/tools/chakra-gitlab-ci-scripts _gitlab-ci-scripts
  # setup basic environment settings, as root
  - _gitlab-ci-scripts/prepare.sh
  # import pgp keys flagged as valid
  - sudo -u builder -E -H _gitlab-ci-scripts/import-validpgpkeys.sh

makepkg:
  stage: build
  script:
    # setup makepkg settings (enable and sync the correct repository), as root
    - _gitlab-ci-scripts/prepare_makepkg.sh
    # the build script can't be run as root, as makepkg would complain...
    - sudo -u builder -E -H _gitlab-ci-scripts/build.sh

  artifacts:
    # expire artifacts per default - the gitlab web frontend can be used to keep
    # artifacts of interest for an unlimited time
    expire_in: 1 week
    paths:
      - ./_repo/gitlab-ci/*.pkg.tar.xz
      - ./_logs/*.log
    name: "$CI_BUILD_NAME"
  cache:
    paths:
      - /var/cache/pacman/pkg
      - ./_sources
  tags:
    - PKGBUILD

gpg:
  stage: sign
  only:
    - branches@chakra/packages/lib32
  artifacts:
    # expire artifacts per default - the gitlab web frontend can be used to keep
    # artifacts of interest for an unlimited time
    expire_in: 1 week
    paths:
      - ./_repo/gitlab-ci/*.pkg.tar.xz.sig
    name: "$CI_BUILD_NAME"
  tags:
    - signature
  script:
     - for pkg in $(find . -type f | grep ".pkg.tar.xz"); do echo "signing $pkg" && echo "$GPG_PASSWORD" | gpg -sb --pinentry-mode loopback --passphrase-fd 0 $pkg; done

deploy_to_testing:
  stage: deploy
  only:
    - branches@chakra/packages/lib32
  except:
    - master@chakra/packages/lib32
  when: manual
  environment:
    name: Testing
    url: https://rsync.chakralinux.org/packages/testing/x86_64/
  variables:
    DEPLOY_SERVER: "$DEPLOY_SERVER"
    SSH_USER: "$SSH_USER"
    SSH_PORT: "$SSH_PORT"
    GPG_PASSWORD: "$GPG_PASSWORD"
    DEST_REPO: "testing"
  tags:
    - rsync
  script:
     - _gitlab-ci-scripts/deploy.sh

deploy_to_stable:
  stage: deploy
  only:
    - master@chakra/packages/lib32
  when: manual
  environment:
    name: Stable
    url: https://rsync.chakralinux.org/packages/lib32/x86_64/
  variables:
    DEPLOY_SERVER: "$DEPLOY_SERVER"
    SSH_USER: "$SSH_USER"
    SSH_PORT: "$SSH_PORT"
    GPG_PASSWORD: "$GPG_PASSWORD"
    DEST_REPO: "lib32"
  tags:
    - rsync
  script:
     - _gitlab-ci-scripts/deploy.sh
